// FirearmLog free-trial counting (ENTITLEMENT_SPEC_2026-09-18.md §5.1-5.2).
//
// Kept separate from licence.ts on purpose: licence.ts is pure cryptographic
// verification of a licence text, this file is the session-counting rule
// that decides whether the wall applies. Neither imports the other.
//
// Arithmetic on records already in memory, never a network call.

import { isLiveSession } from './dashboard.ts';
import { sessionRounds } from './stats.ts';
import type { AppSettings, Session } from './types.ts';

/** Spec §5.2: the tenth live-fire session is free; the wall appears at the
 *  eleventh. */
export const FREE_LIVE_FIRE_SESSIONS = 10;

/**
 * The id form of every session in the bundled sample log: `se-` and exactly
 * three digits (`se-042`), as generated by scripts/make-demo.ts. Every session
 * the app itself creates gets `newId('se')` from src/lib/id.ts instead, which
 * is `se-<base36 time>-<random><counter>` and can never be three digits and
 * nothing else. Two drift guards keep that true: tests/trialGate.test.ts
 * decodes public/demo-dataset.bin and asserts EVERY session in it matches this
 * pattern, and asserts `newId('se')` never does.
 */
export const SAMPLE_SESSION_ID_PATTERN = /^se-\d{3}$/;

/**
 * THE ONE RULE for "this session came with the bundled sample log"
 * (decision 83, 28 September 2026: "the sample log never counts; his own
 * sessions always do"). A session is a sample session if and only if
 * `settings.sampleLogLoaded === true` AND its id has the sample's form.
 *
 * `sampleLogLoaded` alone is NOT enough and is never used alone: the flag stays
 * true while a shooter logs his own sessions on top of the sample, and treating
 * it as an all-or-nothing switch would let him log without limit. The id form
 * alone is also not used: with the flag false (the sample is gone) a session
 * with a three-digit id is not the sample's, so it counts.
 */
export function isSampleSession(
  session: Pick<Session, 'id'>,
  settings: Pick<AppSettings, 'sampleLogLoaded'> | undefined,
): boolean {
  return (
    settings?.sampleLogLoaded === true &&
    typeof session.id === 'string' &&
    SAMPLE_SESSION_ID_PATTERN.test(session.id)
  );
}

/**
 * The live-fire session count the wall is measured against (spec §5.1),
 * derived from the records every time, never stored (decision 12.1). A
 * session counts only when all of these hold:
 *
 *  - it passes `isLiveSession` (dashboard.ts): not planned, not `dry_fire`.
 *    `class` sessions pass this and are counted (decision 12.5). Matches are
 *    not sessions and never reach this function.
 *  - a session in Recently Deleted STILL COUNTS (decision 84, 29 Sep 2026).
 *    Trash is recoverable, so a trashed session is still one of his records:
 *    without this, trash one, log a new one, restore the old one would put an
 *    unlimited number of live sessions past the wall. It stops counting only
 *    when it is gone for good ("Delete Forever", or the 30-day purge), which
 *    is also how an honest mistake leaves the count.
 *  - it was not imported: it carries no `legacy` object at all (decision
 *    12.6). The CSV engine stamps `legacy.importBatch` on every session, and
 *    the migration reader (src/lib/import/pistolTracker.ts) now always stamps
 *    `legacy.importSource: 'migration'`, so neither can pass as "logged here".
 *    Nothing the app does when a shooter logs, edits, converts or restores a
 *    session adds a `legacy` object, so a session he logged himself is never
 *    excluded by this test.
 *  - it did not come with the bundled sample log (`isSampleSession`, decision
 *    83). ONLY the sample's own sessions are excluded, and only while the
 *    sample is loaded. Every session the shooter logs himself counts from the
 *    first one, whether or not the sample is still loaded.
 */
export function countLiveFireSessions(
  sessions: readonly Session[],
  settings: Pick<AppSettings, 'sampleLogLoaded'> | undefined,
): number {
  return countedLiveFireSessions(sessions, settings).length;
}

/**
 * The sessions `countLiveFireSessions` counts, for the wall's figures (spec
 * §5.4: the shooter's own numbers, taken from the same sessions the count
 * uses, so the two can never disagree). The rules are documented on
 * `countLiveFireSessions`.
 */
export function countedLiveFireSessions(
  sessions: readonly Session[],
  settings: Pick<AppSettings, 'sampleLogLoaded'> | undefined,
): Session[] {
  const counted: Session[] = [];
  for (const s of sessions) {
    // Belt and braces: records reach the app through the read boundary, so
    // this should never see a malformed entry, but a defensive skip is
    // cheaper than a crash if one ever does.
    if (s == null || typeof s !== 'object') continue;
    if (s.legacy) continue;
    if (!isLiveSession(s)) continue;
    if (isSampleSession(s, settings)) continue;
    counted.push(s);
  }
  return counted;
}

/** Total rounds across the sessions the count uses (the wall's second figure). */
export function countedLiveFireRounds(
  sessions: readonly Session[],
  settings: Pick<AppSettings, 'sampleLogLoaded'> | undefined,
): number {
  let rounds = 0;
  for (const s of countedLiveFireSessions(sessions, settings)) rounds += sessionRounds(s);
  return rounds;
}

/**
 * Spec §5.2, in code: the wall blocks starting one more live-fire session
 * once an unlicensed shooter has reached the free count. The tenth session
 * itself is never blocked; the eleventh is.
 */
export function wallBlocksNewLiveSession(count: number, licensed: boolean): boolean {
  return !licensed && count >= FREE_LIVE_FIRE_SESSIONS;
}

/**
 * The two figures the wall and the Settings card show. The COUNT is computed
 * first and is allowed to throw (the caller then reports "not ready" rather
 * than a wrong number). The rounds figure is computed in its own try: a record
 * that trips it makes rounds 0 and never touches the count.
 */
export function trialFigures(
  sessions: readonly Session[],
  settings: Pick<AppSettings, 'sampleLogLoaded'> | undefined,
): { count: number; rounds: number } {
  const count = countLiveFireSessions(sessions, settings);
  let rounds = 0;
  try { rounds = countedLiveFireRounds(sessions, settings); } catch { rounds = 0; }
  return { count, rounds };
}

/**
 * Read the sessions and settings and work out the figures, or say plainly that
 * it could not be done. Any failure (the read rejects, or a record trips the
 * count) gives `{ ok: false }`, which the caller shows as "could not be read"
 * and never treats as zero used or as a reason to wall anyone.
 */
export async function loadTrialFigures(
  read: () => Promise<readonly [readonly Session[], Pick<AppSettings, 'sampleLogLoaded'> | undefined]>,
): Promise<{ ok: true; count: number; rounds: number } | { ok: false }> {
  try {
    const [sessions, settings] = await read();
    return { ok: true, ...trialFigures(sessions, settings) };
  } catch {
    return { ok: false };
  }
}
