// Tests for the PractiScore SCSA download-file reader.
//
// The fixtures are TWELVE REAL FILES from eleven clubs, generated by Michael on
// 10 August 2026, with shooter names and membership numbers replaced by
// synthetic ones and everything else byte-identical (see each fixture's header).
//
// Most of what is asserted here is not invented: it is a property some real club
// actually produced, and each test names the club that produced it. That is the
// point of the suite -- a guard written against an imagined file guards nothing.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  parseScsaForm,
  looksLikeScsaForm,
  crossCheckEntry,
  groupEntriesByPerson,
  fileDropWorstHundredths,
  toHundredths,
  SCSA_OFFICIAL_STAGES,
  SCSA_DIVISION_BY_CODE,
  DEGENERATE_MIN_STRINGS,
  type ScsaForm,
} from '../src/lib/scsaForm.ts';

import { Guncraft8stage } from './fixtures/scsa-guncraft-8stage.ts';
import { RedbrushMultigun } from './fixtures/scsa-redbrush-multigun.ts';
import { DeertribeShuffledOrder } from './fixtures/scsa-deertribe-shuffled-order.ts';
import { Scsa363NoMainMatch } from './fixtures/scsa-scsa363-no-main-match.ts';
import { Wnpl6stage } from './fixtures/scsa-wnpl-6stage.ts';
import { DapForeignStageCode } from './fixtures/scsa-dap-foreign-stage-code.ts';
import { MedfordInventedStages } from './fixtures/scsa-medford-invented-stages.ts';
import { BluffsBlankMemberships } from './fixtures/scsa-bluffs-blank-memberships.ts';
import { MedfordClassifiersSameDay } from './fixtures/scsa-medford-classifiers-same-day.ts';
import { TriggerguardManyPenalties } from './fixtures/scsa-triggerguard-many-penalties.ts';
import { GcfgFourStringInvented } from './fixtures/scsa-gcfg-four-string-invented.ts';
import { UspsaDegenerateOneString } from './fixtures/scsa-uspsa-degenerate-one-string.ts';

const STEEL_FIXTURES: [string, string][] = [
  ['guncraft-8stage', Guncraft8stage],
  ['redbrush-multigun', RedbrushMultigun],
  ['deertribe-shuffled-order', DeertribeShuffledOrder],
  ['scsa363-no-main-match', Scsa363NoMainMatch],
  ['wnpl-6stage', Wnpl6stage],
  ['dap-foreign-stage-code', DapForeignStageCode],
  ['medford-invented-stages', MedfordInventedStages],
  ['bluffs-blank-memberships', BluffsBlankMemberships],
  ['medford-classifiers-same-day', MedfordClassifiersSameDay],
  ['triggerguard-many-penalties', TriggerguardManyPenalties],
  ['gcfg-four-string-invented', GcfgFourStringInvented],
];

function ok(text: string, label: string): ScsaForm {
  const r = parseScsaForm(text);
  assert.equal(r.ok, true, `${label} should parse: ${r.ok ? '' : r.message}`);
  return (r as { ok: true; form: ScsaForm }).form;
}

// ---------------------------------------------------------------- detection

test('recognises every real download file, and nothing else', () => {
  for (const [name, text] of STEEL_FIXTURES) {
    assert.equal(looksLikeScsaForm(text), true, name);
  }
  assert.equal(looksLikeScsaForm(UspsaDegenerateOneString), true, 'shape alone, before refusal');
  assert.equal(looksLikeScsaForm(''), false);
  assert.equal(looksLikeScsaForm('Place,Name,USPSA#\n1,Someone,A1'), false);
  assert.equal(looksLikeScsaForm('AAB,2,1,700'), false, 'AAB is not AA');
  // The USPSA text importer uses this to refuse a download file dropped into it.
  assert.equal(looksLikeScsaForm('AA,2,1,700,,,'), true);
});

// ------------------------------------------------------- the whole-file sweep

test('every real Steel file parses, and every entry reconciles with itself', () => {
  let entries = 0;
  let stages = 0;
  for (const [name, text] of STEEL_FIXTURES) {
    const form = ok(text, name);
    assert.ok(form.entries.length > 0, `${name} has entries`);
    for (const e of form.entries) {
      if (e.stages.length === 0) continue;
      const check = crossCheckEntry(e);
      assert.equal(
        check.ok,
        true,
        `${name} competitor ${e.competitorNumber}: ` +
          `stages ${JSON.stringify(check.stageMismatches)} ` +
          `total ${check.totalMismatch} strings ${JSON.stringify(check.stringCountMismatches)}`,
      );
      entries += 1;
      stages += e.stages.length;
    }
  }
  // Not a round number anybody chose -- it is what eleven clubs actually shot.
  // Drop-the-worst and the declared string counts hold on every one.
  assert.equal(entries, 371, 'scored entries across the eleven Steel files');
  assert.equal(stages, 2070, 'scored stages across the eleven Steel files');
});

test("Michael's own match reproduces his published result", () => {
  const form = ok(Guncraft8stage, 'guncraft');
  assert.equal(form.matchDate, '20260809');
  assert.equal(form.clubCode, 'SCSA400');
  const me = form.entries.find((e) => e.membership === 'A185231');
  assert.ok(me, 'found A185231');
  assert.equal(me!.competitorNumber, 24);
  assert.equal(me!.storedDivision, 'Open');
  assert.equal(me!.stages.length, 8);
  assert.equal(me!.fileTotal, 222.41);
  // Recomputed from the raw runs, not read off the file.
  const total = me!.stages.reduce((s, st) => s + (fileDropWorstHundredths(st) ?? 0), 0);
  assert.equal(total, toHundredths(222.41));
  // Overall place within the match, spanning four divisions -- not a division place.
  assert.equal(me!.place, 4);
});

// --------------------------------------------- stage identity: the big lesson

test('a stage number is the running order, NOT the stage (Deer Tribe)', () => {
  const form = ok(DeertribeShuffledOrder, 'deertribe');
  assert.equal(form.clubCode, 'SCSA 003', 'club code arrives quoted, with a space');
  const anyEntry = form.entries.find((e) => e.stages.length === 8)!;
  const first = anyEntry.stages.find((s) => s.stageNumber === 1)!;
  // Deer Tribe hung Roundabout on its bay 1. Keying on the number would have
  // filed six of its eight stages under the wrong name.
  assert.equal(first.officialCode, 'SC-108');
  assert.equal(first.canonicalStageName, 'Roundabout');
  const eighth = anyEntry.stages.find((s) => s.stageNumber === 8)!;
  assert.equal(eighth.officialCode, 'SC-105');
  assert.equal(eighth.canonicalStageName, 'Accelerator');
});

test("a stage's own name is never trusted either (spelling varies by club)", () => {
  const deertribe = ok(DeertribeShuffledOrder, 'deertribe');
  const e = deertribe.entries.find((x) => x.stages.length === 8)!;
  const fiveToGo = e.stages.find((s) => s.officialCode === 'SC-101')!;
  // Deer Tribe writes "Five To Go"; this app calls it "5 to Go".
  assert.equal(fiveToGo.clubStageName, 'Five To Go');
  assert.equal(fiveToGo.canonicalStageName, '5 to Go');
  const smoke = e.stages.find((s) => s.officialCode === 'SC-103')!;
  assert.equal(smoke.clubStageName, 'Smoke And Hope');
  assert.equal(smoke.canonicalStageName, 'Smoke & Hope');
  const pendulum = e.stages.find((s) => s.officialCode === 'SC-106')!;
  assert.equal(pendulum.canonicalStageName, 'Pendulum');
});

test('a four-string stage that is not Outer Limits (GCF&G)', () => {
  const form = ok(GcfgFourStringInvented, 'gcfg');
  const e = form.entries.find((x) => x.stages.length === 5)!;
  const s1 = e.stages.find((s) => s.stageNumber === 1)!;
  // This is the file that proved the app could not have worked out the string
  // count from the stage's name.
  assert.equal(s1.clubStageName, 'Stage 1 Plate Rack Plus');
  assert.equal(s1.declaredStrings, 4);
  assert.equal(s1.officialCode, '');
  assert.equal(s1.canonicalStageName, null);
  assert.equal(s1.runs.length, 4);
  // And the trap: a stage whose name contains "Accelerator" and is not it.
  const notAccel = e.stages.find((s) => s.clubStageName.includes('Not - Accelerator'))!;
  assert.ok(notAccel, 'GCF&G named a stage "Stage 5 Not - Accelerator"');
  assert.equal(notAccel.canonicalStageName, null, 'never matched by name');
  // A stage code hiding inside a NAME while the code column is empty.
  const hotMess = e.stages.find((s) => s.clubStageName.includes('TS-003'))!;
  assert.equal(hotMess.officialCode, '', 'the code column is what counts, not the name');
  assert.equal(hotMess.canonicalStageName, null);
});

test('a stage code outside the SC- family is never forced onto an official stage (DAP)', () => {
  const form = ok(DapForeignStageCode, 'dap');
  const e = form.entries.find((x) => x.stages.length === 5)!;
  const inversion = e.stages.find((s) => s.officialCode === 'TS-004')!;
  assert.ok(inversion, 'DAP ran a TS-004 stage');
  assert.equal(inversion.clubStageName, 'Inversion');
  assert.equal(inversion.canonicalStageName, null);
  // Its official neighbours still resolve.
  assert.equal(e.stages.find((s) => s.officialCode === 'SC-106')!.canonicalStageName, 'Pendulum');
});

test('club-invented stages with no code at all (Medford)', () => {
  const form = ok(MedfordInventedStages, 'medford');
  // The match name carries a comma inside its quotes; a naive split loses it.
  assert.equal(form.matchName, 'Medford Steel Challenge: Aug 9, 2026');
  const e = form.entries.find((x) => x.stages.length === 4)!;
  const invented = e.stages.filter((s) => s.officialCode === '');
  assert.equal(invented.length, 2);
  assert.deepEqual(
    invented.map((s) => s.clubStageName).sort(),
    ['Wall Of Plates', 'You Got This'],
  );
  for (const s of invented) assert.equal(s.canonicalStageName, null);
});

test('the same club on the same day can run two different matches', () => {
  const a = ok(MedfordInventedStages, 'medford main');
  const b = ok(MedfordClassifiersSameDay, 'medford classifiers');
  assert.equal(a.clubCode, b.clubCode);
  assert.equal(a.matchDate, b.matchDate);
  assert.notEqual(a.matchName, b.matchName);
  // Different matches, so a different number of stages -- they are not the same
  // import and must never be collapsed into one.
  assert.equal(a.entries.find((e) => e.stages.length > 0)!.stages.length, 4);
  assert.equal(b.entries.find((e) => e.stages.length > 0)!.stages.length, 2);
});

test('not every file has a Main Match (SCSA363)', () => {
  const form = ok(Scsa363NoMainMatch, 'scsa363');
  assert.equal(form.matches.has(1), false, 'match index 1 is absent');
  assert.deepEqual([...form.matches.keys()].sort((x, y) => x - y), [2, 3]);
  for (const e of form.entries) {
    if (e.matchIndex !== null) assert.ok(e.matchIndex === 2 || e.matchIndex === 3);
  }
});

// ------------------------------------------------------------ people, not names

test('multi-gun is found by membership number, never by name (Red Brush)', () => {
  const form = ok(RedbrushMultigun, 'redbrush');
  const groups = groupEntriesByPerson(form.entries);
  const multi = groups.filter((g) => g.length > 1);
  assert.equal(multi.length, 15, 'fifteen shooters entered twice');
  // Red Brush used no marker at all -- the two entries carry identical names.
  const identicalName = multi.find(
    (g) => g[0].firstName === g[1].firstName && g[0].lastName === g[1].lastName,
  );
  assert.ok(identicalName, 'a shooter entered twice under a byte-identical name');
  // And one person has both entries inside the SAME match, so only the division
  // tells them apart on screen.
  const sameMatch = multi.find((g) => g[0].matchIndex === g[1].matchIndex);
  assert.ok(sameMatch, 'two entries in one match');
  assert.notEqual(sameMatch![0].divisionCode, sameMatch![1].divisionCode);
});

test('blank membership numbers are never grouped (Bluffs)', () => {
  const form = ok(BluffsBlankMemberships, 'bluffs');
  const blanks = form.entries.filter((e) => e.groupKey === null);
  assert.equal(blanks.length, 10, 'ten of sixteen shooters have no number');
  const groups = groupEntriesByPerson(form.entries);
  // Each blank stands alone; welding them together would invent a shooter with
  // ten people's scores.
  for (const b of blanks) {
    const g = groups.find((x) => x.includes(b))!;
    assert.equal(g.length, 1);
  }
});

test('membership numbers group case-insensitively', () => {
  const form = ok(Guncraft8stage, 'guncraft');
  const groups = groupEntriesByPerson(form.entries);
  const multi = groups.filter((g) => g.length > 1);
  assert.equal(multi.length, 3, 'Gun Craft has three multi-gun shooters');
  for (const g of multi) assert.equal(new Set(g.map((e) => e.groupKey)).size, 1);

  // Real files write membership numbers in mixed case -- Gun Craft alone has
  // several. Within one shooter's own two rows the club happened to be
  // consistent, so the data cannot prove the comparison is case-insensitive.
  // Make it prove itself: rewrite one row of a real pair in lower case and
  // confirm the two entries still land together.
  assert.ok(
    form.entries.some((e) => e.membership !== '' && e.membership !== e.membership.toUpperCase()),
    'the file really does carry mixed-case membership numbers',
  );
  const pair = multi[0];
  const number = pair[0].membership;
  const victim = `EC,${pair[1].competitorNumber},${number},`;
  const lowered = Guncraft8stage.replace(
    victim,
    `EC,${pair[1].competitorNumber},${number.toLowerCase()},`,
  );
  assert.notEqual(lowered, Guncraft8stage, 'the rewrite actually landed');
  const after = ok(lowered, 'guncraft, one row lower-cased');
  const regrouped = groupEntriesByPerson(after.entries).filter((g) => g.length > 1);
  assert.equal(regrouped.length, 3, 'still three multi-gun shooters after the case change');
  const changed = regrouped.find((g) =>
    g.some((e) => e.competitorNumber === pair[1].competitorNumber),
  )!;
  assert.equal(changed.length, 2, 'the lower-cased row still groups with its partner');
  // Stored exactly as printed, even though it grouped case-insensitively.
  assert.equal(
    changed.find((e) => e.competitorNumber === pair[1].competitorNumber)!.membership,
    number.toLowerCase(),
  );
});

test('an entered competitor with no scores is present but not importable', () => {
  const form = ok(Guncraft8stage, 'guncraft');
  const unscored = form.entries.filter((e) => e.stages.length === 0);
  assert.equal(unscored.length, 1);
  assert.equal(unscored[0].importable, false);
  assert.equal(unscored[0].blockedReason, 'No scores in this file');
  // His CO row is `CO,13,13,13,,` -- empty match and empty division.
  assert.equal(unscored[0].matchIndex, null);
  assert.equal(unscored[0].divisionCode, '');
});

// ------------------------------------------------------------------ refusals

test('a USPSA match pushed through the Steel form is refused outright', () => {
  const r = parseScsaForm(UspsaDegenerateOneString);
  assert.equal(r.ok, false);
  assert.equal((r as { ok: false; code: string }).code, 'all-degenerate');
  const message = (r as { ok: false; message: string }).message;
  assert.match(message, /drops the worst run/);
  assert.match(message, /Nothing was imported/);
});

test('the degenerate guard keys on the declared string count, never on the times', () => {
  // Deer Tribe has fifteen stages where EVERY run is exactly 30.00 seconds -- a
  // shooter timing out on every run. Legal, real, and it must import.
  const form = ok(DeertribeShuffledOrder, 'deertribe');
  assert.equal(form.degenerateMatches.size, 0);
  let capped = 0;
  for (const e of form.entries) {
    for (const s of e.stages) {
      if (s.runs.length > 0 && s.runs.every((r) => r.time === 30)) {
        capped += 1;
        assert.equal(e.importable, true, 'a fully-capped stage does not block an entry');
      }
    }
  }
  assert.equal(capped, 15);
  assert.equal(DEGENERATE_MIN_STRINGS, 2);
});

test('a truncated file is refused on its own line count', () => {
  const lines = Guncraft8stage.split('\n');
  // Drop a score line from the middle. ZZ still claims the original count.
  const cut = [...lines.slice(0, 200), ...lines.slice(201)].join('\n');
  const r = parseScsaForm(cut);
  assert.equal(r.ok, false);
  assert.equal((r as { ok: false; code: string }).code, 'line-count');
});

test('the line-count check counts the ZZ line itself', () => {
  // The whole, untouched file passes. If the check compared against the count of
  // lines BEFORE ZZ, every valid file would be refused -- so this is the test
  // that keeps the off-by-one honest.
  for (const [name, text] of STEEL_FIXTURES) ok(text, name);
});

test('a file missing a whole section is refused', () => {
  const withoutScores = Guncraft8stage.split('\n')
    .filter((l) => !l.startsWith('SS,'))
    .join('\n');
  const r = parseScsaForm(withoutScores);
  assert.equal(r.ok, false);
  assert.equal((r as { ok: false; code: string }).code, 'incomplete');
});

test('sections out of order are refused', () => {
  const lines = Guncraft8stage.split('\n');
  const scores = lines.filter((l) => l.startsWith('SS,'));
  const rest = lines.filter((l) => !l.startsWith('SS,'));
  // Scores hoisted above the competitor list.
  const scrambled = [rest[0], rest[1], ...scores, ...rest.slice(2)].join('\n');
  const r = parseScsaForm(scrambled);
  assert.equal(r.ok, false);
  assert.equal((r as { ok: false; code: string }).code, 'incomplete');
});

test('anything that is not a download file is refused before anything else', () => {
  for (const junk of ['', '   ', 'hello', 'Place,Name\n1,Someone', '{"json":true}']) {
    const r = parseScsaForm(junk);
    assert.equal(r.ok, false, JSON.stringify(junk));
    assert.equal((r as { ok: false; code: string }).code, 'not-scsa-form');
  }
});

test('two different names for one division code refuses the file', () => {
  // Gun Craft's file contains one completely empty DR row. Overwriting THAT row
  // keeps the line count identical, so this exercises the division check rather
  // than tripping the length check on the way past -- the integrity checks run
  // first by design, and a test that forgets it is testing the wrong guard.
  const empty = Guncraft8stage.split('\n').find(
    (l) => l.startsWith('DR,') && l.replace(/[,\s]/g, '') === 'DR',
  );
  assert.ok(empty, "Gun Craft's empty DR row is still in the fixture");
  const doctored = Guncraft8stage.replace(empty!, 'DR,"Open Class",OPN,1' + ','.repeat(22));
  assert.equal(doctored.split('\n').length, Guncraft8stage.split('\n').length);
  const r = parseScsaForm(doctored);
  assert.equal(r.ok, false);
  assert.equal((r as { ok: false; code: string }).code, 'division-conflict');
});

test('an identical duplicate division row collapses rather than refusing', () => {
  const line = Guncraft8stage.split('\n').find((l) => l.startsWith('DR,') && l.split(',')[2])!;
  const doubled = Guncraft8stage.replace(line, line + '\n' + line);
  // The line count moves, so compare on the refusal reason rather than success.
  const r = parseScsaForm(doubled);
  assert.equal(r.ok, false);
  assert.equal(
    (r as { ok: false; code: string }).code,
    'line-count',
    'the duplicate itself is tolerated; only the length check objects',
  );
});

test('an empty division row defines nothing', () => {
  // Gun Craft's file contains a completely empty DR row. If it created a
  // division keyed by the empty string, competitor 13 -- whose CO row has an
  // empty division -- would silently resolve to it instead of to nothing.
  const form = ok(Guncraft8stage, 'guncraft');
  const unscored = form.entries.find((e) => e.stages.length === 0)!;
  assert.equal(unscored.divisionName, '');
  assert.equal(unscored.storedDivision, null);
});

// ------------------------------------------------------------------ penalties

test('penalty seconds are already inside the run time and are never re-added', () => {
  let penalised = 0;
  let maxPenalties = 0;
  for (const [name, text] of STEEL_FIXTURES) {
    const form = ok(text, name);
    for (const e of form.entries) {
      for (const s of e.stages) {
        for (const r of s.runs) {
          if (r.penalties > 0) {
            penalised += 1;
            maxPenalties = Math.max(maxPenalties, r.penalties);
            // If the seconds were owed on top, this run would be shorter than
            // its own penalty. Not one of them is, anywhere.
            assert.ok(
              r.time >= 3 * r.penalties,
              `${name} comp ${e.competitorNumber} stage ${s.stageNumber}: ` +
                `${r.time}s carrying ${r.penalties} misses`,
            );
          }
        }
        // And the stage total reconciles using the times exactly as written.
        assert.equal(fileDropWorstHundredths(s), toHundredths(s.fileStageTotal));
      }
    }
  }
  assert.equal(penalised, 568, 'penalised strings across the eleven Steel files');
  assert.equal(maxPenalties, 4, 'DAP has a run carrying four misses');
});

test('a run pinned at the 30-second cap can still carry a penalty', () => {
  // The proof that penalties cannot be owed on top: a capped run has no room.
  const form = ok(Guncraft8stage, 'guncraft');
  const found = form.entries.some((e) =>
    e.stages.some((s) => s.runs.some((r) => r.time === 30 && r.penalties > 0)),
  );
  assert.equal(found, true);
});

// ------------------------------------------------------------------ divisions

test('divisions map by code, and the stored names are not renamed', () => {
  // Decision 1 (Michael, 10 Aug 2026): the app keeps its stored singular
  // "Rimfire Revolver Optic" even though the rulebook's Appendix D says
  // "Optics". The export agrees with the app. Recorded, not resolved.
  assert.equal(SCSA_DIVISION_BY_CODE.RRO, 'Rimfire Revolver Optic');
  // The export writes pistol and rifle singular too; the app stores them plural.
  assert.equal(SCSA_DIVISION_BY_CODE.RFPO, 'Rimfire Pistol Optics');
  assert.equal(SCSA_DIVISION_BY_CODE.RFRO, 'Rimfire Rifle Optics');
  // Clubs call OSR "Open Revolver"; the rulebook and this app do not.
  assert.equal(SCSA_DIVISION_BY_CODE.OSR, 'Optical Sight Revolver');
  // Single Stack shares its code with the score-line record type and is still
  // a division; nothing may search the file for the text "SS".
  assert.equal(SCSA_DIVISION_BY_CODE.SS, 'Single Stack');
  assert.equal(SCSA_DIVISION_BY_CODE.PROD, 'Production');
  assert.equal(SCSA_DIVISION_BY_CODE.LTD, 'Limited');
});

test('every division code in every real file is mapped', () => {
  const unmapped = new Set<string>();
  for (const [, text] of STEEL_FIXTURES) {
    const form = ok(text, 'div sweep');
    for (const e of form.entries) {
      if (e.divisionCode === '') continue;
      if (!SCSA_DIVISION_BY_CODE[e.divisionCode]) unmapped.add(e.divisionCode);
    }
  }
  assert.deepEqual([...unmapped], [], 'no real division code goes unmapped');
});

test('a Single Stack entry reads as a division, not as a score line', () => {
  const form = ok(RedbrushMultigun, 'redbrush');
  const ss = form.entries.filter((e) => e.divisionCode === 'SS');
  assert.ok(ss.length > 0, 'Red Brush ran Single Stack');
  for (const e of ss) assert.equal(e.storedDivision, 'Single Stack');
});

// --------------------------------------------------------------- stage table

test('the official stage table matches the app, including the four-string one', () => {
  assert.equal(Object.keys(SCSA_OFFICIAL_STAGES).length, 8);
  assert.equal(SCSA_OFFICIAL_STAGES['SC-104'].name, 'Outer Limits');
  assert.equal(SCSA_OFFICIAL_STAGES['SC-104'].strings, 4);
  for (const [code, s] of Object.entries(SCSA_OFFICIAL_STAGES)) {
    if (code !== 'SC-104') assert.equal(s.strings, 5, code);
  }
});

test('every official stage in the real files declares the expected string count', () => {
  for (const [name, text] of STEEL_FIXTURES) {
    const form = ok(text, name);
    for (const e of form.entries) {
      for (const s of e.stages) {
        const official = SCSA_OFFICIAL_STAGES[s.officialCode];
        if (!official) continue;
        assert.equal(
          s.declaredStrings,
          official.strings,
          `${name} stage ${s.stageNumber} (${s.officialCode})`,
        );
      }
    }
  }
});

// ------------------------------------------------------------------- numbers

test('times are compared in whole hundredths, never as text or loose decimals', () => {
  // The same value appears as `30.00`, `30.0` and `30` in real files.
  assert.equal(toHundredths(30), toHundredths(30.0));
  assert.equal(toHundredths(7.42), 742);
  assert.equal(toHundredths(0.1) + toHundredths(0.2), toHundredths(0.3));
});

test('the cross-check catches a doctored total', () => {
  const form = ok(Guncraft8stage, 'guncraft');
  const me = form.entries.find((e) => e.membership === 'A185231')!;
  const tampered = {
    ...me,
    stages: me.stages.map((s, i) => (i === 0 ? { ...s, fileStageTotal: s.fileStageTotal + 1 } : s)),
  };
  const check = crossCheckEntry(tampered);
  assert.equal(check.ok, false);
  assert.deepEqual(check.stageMismatches, [tampered.stages[0].stageNumber]);
});

test('the cross-check catches a run removed from a stage', () => {
  const form = ok(Guncraft8stage, 'guncraft');
  const me = form.entries.find((e) => e.membership === 'A185231')!;
  const tampered = {
    ...me,
    stages: me.stages.map((s, i) => (i === 0 ? { ...s, runs: s.runs.slice(1) } : s)),
  };
  const check = crossCheckEntry(tampered);
  assert.equal(check.ok, false);
  assert.ok(check.stringCountMismatches.length > 0, 'the declared count no longer matches');
});

test('the declared string count comes from the FILE, not from the runs present', () => {
  // A MUTATION FOUND THIS GAP, AND THEN FOUND IT AGAIN. Deriving the count from
  // however many runs happen to be in the row makes it agree with itself by
  // construction, so the cross-check comparing the two could never fail.
  //
  // Killing that mutation needs a stage where the two sourcings DISAGREE, and
  // the first attempt at this test used an OFFICIAL stage -- where the file's
  // declaration and the official table say the same thing, so both a right and
  // a wrong implementation pass. It has to be a CLUB-INVENTED stage, which has
  // no official count to fall back on: GCF&G's four-string "Plate Rack Plus".
  const line = GcfgFourStringInvented.split('\n').find((l) => l.startsWith('SS,1,1,1,'))!;
  assert.ok(line, "a score row on GCF&G's four-string invented stage");
  const cols = line.split(',');
  assert.equal(cols.length, 26);
  cols[14] = '';
  cols[15] = '';
  cols[16] = ''; // the fourth run's time, penalty count and flag
  const doctored = GcfgFourStringInvented.replace(line, cols.join(','));
  assert.equal(doctored.split('\n').length, GcfgFourStringInvented.split('\n').length);

  const form = ok(doctored, 'gcfg with one run removed');
  const entry = form.entries.find((e) => e.competitorNumber === 1)!;
  const stage1 = entry.stages.find((s) => s.stageNumber === 1)!;
  assert.equal(stage1.canonicalStageName, null, 'a club-invented stage, so no official count');
  assert.equal(stage1.runs.length, 3, 'only three runs survive in the row');
  assert.equal(stage1.declaredStrings, 4, 'but the file still DECLARES four');
  const check = crossCheckEntry(entry);
  assert.equal(check.ok, false);
  assert.deepEqual(check.stringCountMismatches, [1], 'the disagreement is reported');
});

test('an official stage keeps the file as its authority too', () => {
  const line = Guncraft8stage.split('\n').find((l) => l.startsWith('SS,1,1,24,'))!;
  const cols = line.split(',');
  cols[17] = '';
  cols[18] = '';
  cols[19] = '';
  const form = ok(Guncraft8stage.replace(line, cols.join(',')), 'guncraft, one run removed');
  const me = form.entries.find((e) => e.membership === 'A185231')!;
  const stage1 = me.stages.find((s) => s.stageNumber === 1)!;
  assert.equal(stage1.runs.length, 4);
  assert.equal(stage1.declaredStrings, 5);
  assert.deepEqual(crossCheckEntry(me).stringCountMismatches, [1]);
});

test('a naive comma split would corrupt a real match name', () => {
  // Two of the sample match names carry a comma inside their quotes. This is
  // the assertion that fails if the reader ever stops using a real CSV parser.
  const form = ok(MedfordInventedStages, 'medford');
  assert.equal(form.matchName, 'Medford Steel Challenge: Aug 9, 2026');
  assert.equal(form.matchDate, '20260809', 'the date column is still the date');
  assert.equal(form.clubCode, 'SCSA394');
  // What a naive split on commas would have produced instead:
  const naive = MedfordInventedStages.split('\n')[1].split(',');
  assert.notEqual(naive[4], '20260809', 'a naive split really does shift the columns');
});
