// Truncated old-style fixture: the header row has been dropped, leaving only
// data rows and footer. Simulates a paste that missed the top of the table.
// Contains short division codes (CO, LO, O) and abbreviated PF (Min) but:
//   - No full division name adjacent to MINOR/MAJOR
//   - No lines matching /^d+-name/
//   - None of the page furniture strings
// Therefore looksLikeNewStyleResults must return false on this.
export const TAKE_AIM_MINI_2026_08_03_TRUNCATED_OLDSTYLE = `1	Olinchak, Matt			LO	Min		347.0388	100.0000%
2	Slack, Chris			CO	Min		318.6548	91.8211%
3	Buehler, Mike			LO	Min		313.9015	90.4514%
4	Boyd, Richard			LO	Min		260.3304	75.0148%
5	Tutko, Tank			CO	Min		249.0468	71.7634%
6	Pepperoni, Les			CO	Min		232.7610	67.0706%
7	Benderson, Evan			CO	Min		229.9631	66.2644%
8	Kalash, Gypsy			LO	Min		224.3339	64.6423%
9	Cherry, Ian			O	Min		223.0822	64.2816%
10	Hobson, Chris			CO	Min		216.2277	62.3065%
11	Richard, Paul			LO	Min		207.0612	59.6651%
12	Mcdonald, Matt			CO	Min		206.2361	59.4274%
13	Savvides, Tyler			O	Min		180.3783	51.9764%
14	Scott, Brad			CO	Min		139.2876	40.1360%
15	Pelayo, Ken			O	Min		132.5542	38.1958%
16	Coil, Ausi			CO	Min		130.6216	37.6389%
17	Buehler, Jon			CO	Min		130.2281	37.5255%
18	Minik, Michael			CO	Min		129.7697	37.3934%
19	Fernandez, Elmo			CO	Min		125.4317	36.1434%
20	Phillips, Bill			CO	Min		107.8967	31.0907%
21	Nichols, Taylor			CO	Min		96.2916	27.7466%
Generated by PractiScore 2.3.14+318 Am
`;
